---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Run fleet-dell-fan-metrics
  ansible.builtin.systemd:
    name: fleet-dell-fan-metrics.service
    state: started
  when: not ansible_check_mode
